name: "Documentation"

on: [push]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Documentation
        id: documentation
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_output_file: README.md
          tf_docs_output_method: replace
          tf_docs_git_push: 'false'

      - name: Check up-to-date
        env:
          NUM_CHANGED: ${{ steps.documentation.outputs.num_changed }}
        run: 'if [ "$NUM_CHANGED" -eq 0 ]; then echo "Documentation up-to-date"; else echo "You must update documentation"i; git diff --cached; exit 1; fi'
